[theme]

# Primary accent for interactive elements
primaryColor = '#063971'

# Background color for the main content area
backgroundColor = '#f3f2f2'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#3569aa'

# Color used for almost all text
textColor = '#000000'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace)
# Default: "sans serif"
font = "Serif"
